[package]
name = "logic_trioxide"
version = "0.1.0"
edition = "2021"
authors = ["Anurag"]
description = "A simple Logic Gate simulating Library"

[dependencies]

[lib]
name = "logic_o3"
path = "./src/lib.rs"

